apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tayyaba-keystone/DockerRailsTodo.git'  # your todo app repo
    path: manifests   # adjust this if your manifests are in another folder, or root folder if manifests are there
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

